apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: kubernaizing
type: Opaque
stringData:
  username: REPLACE_WITH_MONGO_USERNAME
  password: REPLACE_WITH_MONGO_PASSWORD
  mongo-uri: mongodb://REPLACE_WITH_MONGO_USERNAME:REPLACE_WITH_URL_ENCODED_MONGO_PASSWORD@mongo:27017/todos?authSource=admin
